/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alura;

import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Interfaz extends javax.swing.JFrame {
    PesoCol peso = new PesoCol();
    Dolar dolar = new Dolar();
    Euro euro = new Euro();
    LibrasEsterlinas libras = new LibrasEsterlinas();
    WomSurCorea wom = new WomSurCorea();
    YenJap yen = new YenJap();
    Distancia distancia = new Distancia();
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTexCantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONVERSOR DIVISAS");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cantidad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jTexCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(jTexCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 130, -1));

        jLabel2.setText("DE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Peso Colombiano", "Dolar", "Euro", "Libras Esterlinas", "Wom Surcoreano", "Yen Japones" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel3.setText("A");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 10, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Peso Colombiano", "Dolar", "Euro", "Libras Esterlinas", "Wom Surcoreano", "Yen Japones" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel4.setText("TOTAL: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jTextTotal.setEditable(false);
        jPanel1.add(jTextTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 128, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Conversor de Divisas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jTabbedPane1.addTab("Divisas", jPanel1);

        jLabel6.setText("Distancia");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel7.setText("DE");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Metros", "Kilometros", "Millas" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel8.setText("A");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Metros", "Kilometros", "Millas" }));

        jLabel9.setText("TOTAL");

        jTextField2.setEditable(false);

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButton2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Distancia", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTexCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexCantidadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jTexCantidad.getText().equals("")){
            JOptionPane.showMessageDialog(null, "DEBES INGRESAR UN VALOR POSITIVO");
        }else{
            
        String Opcion1 = jComboBox1.getSelectedItem().toString() + " a " +jComboBox2.getSelectedItem().toString();
        int cantidad = Integer.parseInt(jTexCantidad.getText());
        
        if(cantidad<=0){
            JOptionPane.showMessageDialog(null, "DEBES INGRESAR UN VALOR POSITIVO");
        }else{
                
            switch(Opcion1) {
                
                //PESO
                case "Peso Colombiano a Dolar":
                    jTextTotal.setText(String.valueOf(peso.Convertir(peso.getTasaPesoDolar(), cantidad)));
                    break;
                case "Peso Colombiano a Euro":
                    jTextTotal.setText(String.valueOf(peso.Convertir(peso.getTasaPesoEuro(), cantidad)));
                    break;
                case "Peso Colombiano a Libras Esterlinas":
                    jTextTotal.setText(String.valueOf(peso.Convertir(peso.getTasaPesoLibrasEs(), cantidad)));
                    break;
                case "Peso Colombiano a Wom Surcoreano":
                    jTextTotal.setText(String.valueOf(peso.Convertir(peso.getTasaPesoWomCorea(), cantidad)));
                    break;
                case "Peso Colombiano a Yen Japones":
                    jTextTotal.setText(String.valueOf(peso.Convertir(peso.getTasaPesoYenJap(), cantidad)));
                    break;
                    
                    //DOLAR
                case "Dolar a Peso Colombiano":
                    jTextTotal.setText(String.valueOf( dolar.Convertir(dolar.getDolarPeso(), cantidad)));
                    break;
                case "Dolar a Euro":
                    jTextTotal.setText(String.valueOf( dolar.Convertir(dolar.getDolarEuro(), cantidad)));
                    break;
                case "Dolar a Libras Esterlinas":
                    jTextTotal.setText(String.valueOf( dolar.Convertir(dolar.getDolarLibras(), cantidad)));
                    break;
                case "Dolar a Wom Surcoreano":
                    jTextTotal.setText(String.valueOf( dolar.Convertir(dolar.getDolarWomCorea(), cantidad)));
                    break;
                case "Dolar a Yen Japones":
                    jTextTotal.setText(String.valueOf( dolar.Convertir(dolar.getDolarYenJap(), cantidad)));
                    break;
                    
                    //EURO
                case "Euro a Peso Colombiano":
                    jTextTotal.setText(String.valueOf( euro.Convertir(euro.getEuroPeso(), cantidad)));
                    break;
                case "Euro a Dolar":
                    jTextTotal.setText(String.valueOf( euro.Convertir(euro.getEuroDolar(), cantidad)));
                    break;
                case "Euro a Libras Esterlinas":
                    jTextTotal.setText(String.valueOf( euro.Convertir(euro.getEurolibras(), cantidad)));
                    break;
                case "Euro a Wom Surcoreano":
                    jTextTotal.setText(String.valueOf( euro.Convertir(euro.getEuroWom(), cantidad)));
                    break;
                case "Euro a Yen Japones":
                    jTextTotal.setText(String.valueOf( euro.Convertir(euro.getEuroYen(), cantidad)));
                    break;
                    
                    //LIBRAS ESTERLINAS
                case "Libras Esterlinas a Peso Colombiano":
                    jTextTotal.setText(String.valueOf( libras.Convertir(libras.getLibrasPeso(), cantidad)));
                    break;
                case "Libras Esterlinas a Dolar":
                    jTextTotal.setText(String.valueOf( libras.Convertir(libras.getLibrasDolar(), cantidad)));
                    break;
                case "Libras Esterlinas a Euro":
                    jTextTotal.setText(String.valueOf( libras.Convertir(libras.getLibrasEuros(), cantidad)));
                    break;
                case "Libras Esterlinas a Wom Surcoreano":
                    jTextTotal.setText(String.valueOf( libras.Convertir(libras.getLibrasWomCorea(), cantidad)));
                    break;
                case "Libras Esterlinas a Yen Japones":
                    jTextTotal.setText(String.valueOf( libras.Convertir(libras.getLibrasYen(), cantidad)));
                    break;
                    
                    //WOM Surcoreano
                case "Wom Surcoreano a Peso Colombiano":
                    jTextTotal.setText(String.valueOf( wom.Convertir(wom.getWomPeso(), cantidad)));
                    break;
                case "Wom Surcoreano a Dolar":
                    jTextTotal.setText(String.valueOf( wom.Convertir(wom.getWomDolar(), cantidad)));
                    break;
                case "Wom Surcoreano a Euro":
                    jTextTotal.setText(String.valueOf( wom.Convertir(wom.getWomEuro(), cantidad)));
                    break;
                case "Wom Surcoreano a Libras Esterlinas":
                    jTextTotal.setText(String.valueOf( wom.Convertir(wom.getWomLibras(), cantidad)));
                    break;
                case "Wom Surcoreano a Yen Japones":
                    jTextTotal.setText(String.valueOf( wom.Convertir(wom.getWomYen(), cantidad)));
                    break;
                    
                    //YEN Japones
                case "Yen Japones a Peso Colombiano":
                    jTextTotal.setText(String.valueOf( yen.Convertir(yen.getYenPeso(), cantidad)));
                    break;
                case "Yen Japones a Dolar":
                    jTextTotal.setText(String.valueOf( yen.Convertir(yen.getYenDolar(), cantidad)));
                    break;
                case "Yen Japones a Euro":
                    jTextTotal.setText(String.valueOf( yen.Convertir(yen.getYenEuro(), cantidad)));
                    break;
                case "Yen Japones a Libras Esterlinas":
                    jTextTotal.setText(String.valueOf( yen.Convertir(yen.getYenLibras(), cantidad)));
                    break;
                case "Yen Japones a Wom Surcoreano":
                    jTextTotal.setText(String.valueOf( yen.Convertir(yen.getYenWom(), cantidad)));
                    break;
                    
                default:
                    //System.out.println("Opción inválida");
                    JOptionPane.showMessageDialog(null, "SELECCIONA UNA OPCION VALIDA");
                    break;
            }
            
        }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "DEBES INGRESAR UN VALOR");
        }else{
            
        String Opcion1 = jComboBox3.getSelectedItem().toString() + " a " +jComboBox4.getSelectedItem().toString();
        double cantidad = Double.parseDouble(jTextField1.getText());
        
        if(cantidad<=0){
            JOptionPane.showMessageDialog(null, "DEBES INGRESAR UN VALOR POSITIVO");
        }else{       
            
            switch(Opcion1) {
                    
                    //YEN Japones
                case "Metros a Kilometros":
                    jTextField2.setText(String.valueOf( distancia.MetrosKilometros(cantidad)));
                    break;
                case "Metros a Millas":
                    jTextField2.setText(String.valueOf( distancia.MetrosMillas(cantidad)));
                    break;
                case "Kilometros a Metros":
                    jTextField2.setText(String.valueOf( distancia.KilometrosMetros(cantidad)));
                    break;
                case "Kilometros a Millas":
                    jTextField2.setText(String.valueOf( distancia.KilometroAMillas(cantidad)));
                    break;
                case "Millas a Metros":
                    jTextField2.setText(String.valueOf( distancia.MillasMetros(cantidad)));
                    break;
                case "Millas a Kilometros":
                    jTextField2.setText(String.valueOf( distancia.MillasKilometros(cantidad)));
                    break;                
                    
                default:
                    //System.out.println("Opción inválida");
                    JOptionPane.showMessageDialog(null, "SELECCIONA UNA OPCION VALIDA");
                    break;
            }
            
        }
        
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTexCantidad;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextTotal;
    // End of variables declaration//GEN-END:variables
}
